# Generated by Django 4.0.6 on 2026-01-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=50)),
                ('Duracion', models.CharField(max_length=20)),
                ('Cupo', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('identidad', models.CharField(max_length=10)),
                ('fecha_Matricula', models.DateField(auto_now_add=True)),
                ('Curso_Matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Matriculas', to='Cursos.cursos')),
            ],
        ),
    ]
