# Generated by Django 4.2.7 on 2026-01-21 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_alter_cursos_cupo_alter_cursos_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='Cupo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Duracion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo debe contener letras', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')]),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='Nombre',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='El nombre solo debe contener letras', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')]),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='identidad',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos numéricos', regex='^\\d{10}$')]),
        ),
    ]
