# Generated by Django 4.2.7 on 2026-01-22 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_alter_cursos_cupo_alter_cursos_duracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='instructores/')),
            ],
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Cupo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Duracion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='Nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='identidad',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='cursos',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='Cursos.instructor'),
        ),
    ]
